feat(drivers): add fine-grained control for link signing
alist-org/alist pull request #3924
Opened 2023-03-22 20:26 UTC by WhiteElytra

Provide link signature authentication option for Local Driver.
Reuse the original Sign function for link signature.
Clear the sign parameter for URLs that don't require a signature.

2023-03-23 04:46 UTC, WhiteElytra commented
After testing, only proxy url works, I will push a new commit to support direct url. (Tonight)

2023-03-23 05:22 UTC, Xhofe commented
I can't understand why you do this?

2023-03-23 08:44 UTC, WhiteElytra commented
ok i'll try it tonight.

2023-03-23 14:55 UTC, WhiteElytra commented
It's done! Tested on Local Driver and Aliyundrive Driver.

2023-03-24 06:53 UTC, Xhofe requested changes

2023-03-24 06:53 UTC, Xhofe commented on public/dist/README.md
> -## Put dist of frontend here.
Do not delete this file please, otherwise it will cause a ci failure.

2023-03-24 06:53 UTC, Xhofe commented on server/handles/fsread.go
>  			if storage.GetStorage().DownProxyUrl != "" {
For `DownProxyUrl`, sign param is required regardless of whether sign is turned on in the settings due to its implementation.

2023-03-24 06:53 UTC, Xhofe commented on server/handles/fsread.go
> +func needSign(meta *model.Meta, path string) bool {
This function is duplicated with `isEncrypt`, consider merging

2023-03-24 14:01 UTC, Xhofe approved these changes

2023-03-24 14:44 UTC, merged