允许用户通过填写 Google Service Account 文件的位置或所在路径, 通过使用 Google Service Account 管理 Google Drive文件
alist-org/alist pull request #4360
Opened 2023-05-10 02:51 UTC by orangejx

允许用户通过填写 Google Service Account 文件的位置或所在路径, 通过使用 Google Service Account 管理 Google Drive文件.

用户可以将Google Service Account文件路径或所在文件夹路径填入 Refresh Token 输入框, Google Drive 驱动即可自动识别. 并且不会影响原本填入 Refresh Token 的用户.

以及 Google Service Account 格式为默认 Google Cloud 默认格式, 样本如下:
```
{
  "type": "service_account",
  "project_id": "saf-xxx***xxx",
  "private_key_id": "0***2",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwgg***\n-----END PRIVATE KEY-----\n",
  "client_email": "mfc-xxx***xxx@saf-xxx***xxx.iam.gserviceaccount.com",
  "client_id": "1***6",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/mfc-xxx***xxx%40saf-xxx***xxx.iam.gserviceaccount.com"
}
```

2023-05-11 13:52 UTC, orangejx commented
> 测试过可以吗 因为我不是很了解sa

测试过, 完全可用! 我在TG私聊你啦

2023-05-11 14:36 UTC, Xhofe requested changes

2023-05-11 14:36 UTC, Xhofe commented on drivers/google_drive/util.go
> +			log.Fatal("Error when opening file: ", err)
遇到err 直接 return err就行，不用Fatal，可能会导致程序退出。

2023-05-11 14:36 UTC, Xhofe commented on drivers/google_drive/util.go
> +			log.Fatal("Error during Unmarshal(): ", err)
同上

2023-05-11 14:36 UTC, Xhofe commented on drivers/google_drive/util.go
> +			fmt.Println(err)
日志统一使用logrus。

2023-05-11 14:36 UTC, Xhofe commented on drivers/google_drive/util.go
> +		log.Error("You dont have permission to get the Google Service Account file or folder")
这里的错误可能也需要抛出。

2023-05-11 20:13 UTC, orangejx commented
> > > 测试过可以吗 因为我不是很了解sa
> > 
> > 
> > 测试过, 完全可用! 我在TG私聊你啦
> 
> 👌测试过就行

改好啦, 麻烦 dalao 再次审核一下啦

2023-05-12 06:35 UTC, Xhofe approved these changes

2023-05-12 06:47 UTC, merged