feat(139): support new personal cloud api
alist-org/alist pull request #5690
Opened 2023-12-14 05:41 UTC by linepro6

- 支持中国移动云盘新版个人云 API（测试与 PC 网页版和手机客户端列出文件一致）
- 支持中国移动云盘新版个人云的 video_preview 方法
- 中国移动云盘存储中的根文件夹 ID 可不填，默认使用根目录。

2023-12-16 07:41 UTC, xhofe requested changes

2023-12-16 07:41 UTC, xhofe commented on drivers/139/driver.go
> +		return nil
这里没有初始化Account，但是后面使用了 会有问题的吧 有测试过嘛

2023-12-16 08:31 UTC, linepro6 commented on drivers/139/driver.go
> +		return nil
测试过的。新版个人云 API 不需要 Account 参数，所以没初始化。

2023-12-16 08:39 UTC, xhofe commented on drivers/139/driver.go
> +		return nil
<img width="1018" alt="image" src="https://github.com/alist-org/alist/assets/36558727/0f24469f-c846-4993-8bf2-8f39bc1570bf">
但是试了一下会报错，https://github.com/alist-org/alist/actions/runs/7222365771?pr=5690 这个版本

2023-12-16 08:41 UTC, linepro6 commented on drivers/139/driver.go
> +		return nil
可能和账号注册时间有关系。看看 https://yun.139.com/ 下面官方的网页用的是旧版 API 还是新版 API 请求的？

2023-12-16 08:42 UTC, xhofe commented on drivers/139/driver.go
> +		return nil
有可能 我的是旧的

2023-12-16 08:43 UTC, xhofe approved these changes

2023-12-16 08:56 UTC, merged

2023-12-20 08:00 UTC, MerceKrist commented
请教，使用person new类型，提示failed get objs: failed to list objs: 用户不存在
使用个人云类型，可以打开，但是浏览器关闭就会失效。

2023-12-31 11:56 UTC, linepro6 commented
> 请教，使用person new类型，提示failed get objs: failed to list objs: 用户不存在 使用个人云类型，可以打开，但是浏览器关闭就会失效。

personal new 应该是需要比较新的账号才能用，你可以登录官方网页看看请求的是老接口还是新接口。找不到getDisk的就是新接口。
登录过期的问题，可能你需要注意不要在浏览器里退出登录。你可以试试开个无痕模式登录拿到token以后直接关闭无痕窗口。

2024-01-06 07:34 UTC, anwen-anyi commented
你好  这个新接口如何使用呢

老账户如何切换到新接口呢？ 还能看到`getDisk`这个接口